name: Deploy al servidor

on:
  push:
    branches: [ main ]

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          remote_path: ${{ secrets.SSH_REMOTE_PATH }}
          local_path: ${{ secrets.SSH_LOCAL_PATH }}
          ssh_private_key: ${{ secrets.PRIVATE_SSH_KEY }}
    